- name: Running all configured dotfiles
  become: true
  hosts: local
  pre_tasks:
    - name: Get the docker repsitory
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test
        state: present
    - name: Update machine
      apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: yes
      tags: ['update']
    - name: Install utility commands
      apt:
        name: 
          - curl
          - fonts-powerline
  roles:
    - role: git
      tags: ['git', 'vps']
    - role: zsh
      tags: ['zsh', 'vps']
    - role: bat
      tags: ['bat', 'vps']
    - role: keybase
      tags: ['keybase']
    - role: screenshot
      tags: ['screenshot']
    - role: node
      tags: ['node', 'vps']
    - role: python
      tags: ['python', 'vps']
    - role: haskell
      tags: ['haskell']
    - role: vscode
      tags: ['vscode']
    - role: nickjj.docker
      tags: ['docker', 'vps']

