- name: Running all configured dotfiles
  become: true
  hosts: local
  pre_tasks:
    - name: 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test
        state: present
    - name: Update machine
      apt:
        upgrade: yes
        update_cache: yes
      tags: ['update']
  roles:
    - role: git
      tags: ['git']
    - role: zsh
      tags: ['zsh']
    - role: bat
      tags: ['bat']
    - role: node
      tags: ['node']
    - role: haskell
      tags: ['haskell']
    - role: vscode
      tags: ['vscode']
    - role: nickjj.docker
      tags: ['docker']

