- name: Check if zshrc already exists
  stat:
    path: "{{ home }}/.zshrc"
  register: zshrc

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zshrc.bak"
  when: zshrc.stat.exists

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Download oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ zsh.installer_location }}"
    force: no
  when: zshrc.stat.exists == False

- name: Install oh-my-zsh
  script: "{{ zsh.installer_location }}"
  become: yes
  when: zshrc.stat.exists == False

- name: Download spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ spaceship_dest }}"
    clone: yes

- name: Symlink spaceship theme
  file:
    src: "{{ spaceship_dest }}/spaceship.zsh-theme"
    dest: "{{ zsh.dir }}/themes/spaceship.zsh-theme"
    state: link
    force: yes
    follow: no

- name: Download autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ autosuggestions_dest }}"
    clone: yes

- name: Download syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ syntax_highlighting_dest }}"
    clone: yes

- name: Copy .zshrc
  template:
    src: ".zshrc"
    dest: "{{ home }}/.zshrc"
