- name: Installing git
  apt:
    name: git
    state: present
    
- name: Check if gitconfig exists
  stat: path="{{ dotfiles_user_home }}/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "{{ dotfiles_user_home }}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "{{ home }}/.gitconfig"
