- name: Check if keybase is installed
  shell: command -v keybase >/dev/null 2>&1
  register: keybase_exists
  ignore_errors: yes
  changed_when: "keybase_exists == 0"

- name: Install keybase
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb
  when: keybase_exists is failed
  become: yes
